### PR TITLE
Fix support for appOptions.el being provided as a domElement. Resolves #42

### LINKED ISSUE #42: appOptions.el doesn't work if provided as a dom element
See related https://github.com/single-spa/single-spa/issues/478#issuecomment-599542685

### PR DESCRIPTION
**Pull request by joeldenning**
See #42

### CODE REVIEW

File: src/single-spa-vue.js [hunk 1]
```diff
@@ -75,6 +75,10 @@ function mount(opts, mountedInstances, props) {
         }
       } else {
         domEl = appOptions.el;
+        if (!domEl.id) {
+          domEl.id = `single-spa-application:${props.name}`;
```
Comment (TheMcMurder) [inline src/single-spa-vue.js]: This is behavior already implemented in `single-spa-react` yes?

Comment (joeldenning) [reply src/single-spa-vue.js]: Yes, but this is single-spa-vue
